name = "wasm-worker"
type = "rust"
# to get the account id and zone id, go to dash.cloudflare.com,
# select your domain, click 'Overview', and scroll to the bottom of the page
account_id = "00000000000000000000000000000000"
zone_id = "00000000000000000000000000000000"
workers_dev = false
# The route should match the route setup on dash.cloudflare.com
route = "my.domain.com/*"
